trigger:
  - master

jobs:

  - job: 'vs2015_clang_release'
    pool:
      # NOTE: this is the same image currently used by conda.
      # Like conda, we'll be using vs2015, not vs2017. If we
      # try to use the vs2015 image, we get some DLL errors
      # related to dbgeng, which *I think* are due to the
      # fact that the vs2015 image is using an older version of
      # the OS.
      vmImage: 'vs2017-win2016'
    timeoutInMinutes: 360
    steps:

      # Install Chocolatey (https://chocolatey.org/install#install-with-powershellexe)
      - powershell: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          Write-Host "##vso[task.setvariable variable=PATH]$env:PATH"
          choco --version
        displayName: "Install Chocolatey"

      # Install Miniconda
      - script: |
          choco install miniconda3 --yes
          set PATH=C:\tools\miniconda3\Scripts;C:\tools\miniconda3;C:\tools\miniconda3\Library\bin;%PATH%
          echo '##vso[task.setvariable variable=PATH]%PATH%'
          set LIB=C:\tools\miniconda3\Library\lib;%LIB%
          echo '##vso[task.setvariable variable=LIB]%LIB%'
          conda --version
        displayName: "Install Miniconda"

      # Configure Miniconda
      - script: |
          conda config --set always_yes yes
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda info
        displayName: "Configure Miniconda"

      # Create conda enviroment
      # Note: conda activate doesn't work here, because it creates a new shell!
      - script: |
          conda install cmake ^
                        clangdev ^
                        obake-devel ^
                        boost-cpp ^
                        ninja ^
                        python=3.7
          conda list
        displayName: "Install conda packages"

      # Install pybind11.
      - script: |
          setlocal EnableDelayedExpansion
          git clone https://github.com/pybind/pybind11.git
          cd pybind11
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release ^
                   -DCMAKE_PREFIX_PATH=C:\tools\miniconda3\Library ^
                   -DCMAKE_INSTALL_PREFIX=C:\tools\miniconda3\Library ^
                   -DPYBIND11_TEST=NO
          cmake --build . --config Release --target install
          cd ..
          cd ..
        displayName: "Install pybind11"

      # Configure, build and test.
      - script: |
          setlocal EnableDelayedExpansion
          call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
          mkdir build
          cd build
          cmake .. -G Ninja ^
                -DCMAKE_BUILD_TYPE=Release ^
                -DCMAKE_C_COMPILER=clang-cl ^
                -DCMAKE_CXX_COMPILER=clang-cl ^
                -DCMAKE_PREFIX_PATH=C:\tools\miniconda3\Library ^
                -DCMAKE_INSTALL_PREFIX=C:\tools\miniconda3\Library
          cmake --build . -- -v
          python -c "import obake; obake.test.run_test_suite()"
        displayName: "Configure, build and test"
  - job: 'vs2019_relwithdebinfo'
    pool:
      vmImage: 'windows-2019'
    timeoutInMinutes: 360
    steps:

      # Install Chocolatey (https://chocolatey.org/install#install-with-powershellexe)
      - powershell: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          Write-Host "##vso[task.setvariable variable=PATH]$env:PATH"
          choco --version
        displayName: "Install Chocolatey"

      # Install Miniconda
      - script: |
          choco install miniconda3 --yes
          set PATH=C:\tools\miniconda3\Scripts;C:\tools\miniconda3;C:\tools\miniconda3\Library\bin;%PATH%
          echo '##vso[task.setvariable variable=PATH]%PATH%'
          set LIB=C:\tools\miniconda3\Library\lib;%LIB%
          echo '##vso[task.setvariable variable=LIB]%LIB%'
          conda --version
        displayName: "Install Miniconda"

      # Configure Miniconda
      - script: |
          conda config --set always_yes yes
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda info
        displayName: "Configure Miniconda"

      # Create conda enviroment
      # Note: conda activate doesn't work here, because it creates a new shell!
      - script: |
          conda install cmake ^
                        obake-devel ^
                        boost-cpp ^
                        pybind11 ^
                        ninja ^
                        python=3.7
          conda list
        displayName: "Install conda packages"

      # Configure, build and test.
      - script: |
          setlocal EnableDelayedExpansion
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" ^
                -DCMAKE_PREFIX_PATH=C:\tools\miniconda3\Library ^
                -DCMAKE_INSTALL_PREFIX=C:\tools\miniconda3\Library
          cmake --build . --config RelWithDebInfo
          python -c "import obake; obake.test.run_test_suite()"
        displayName: "Configure, build and test"
