version: 2

jobs:
  bionic_py38_conda:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_py38_conda.sh
  bionic_py37_conda:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_py37_conda.sh

workflows:
  version: 2
  all_builds:
    jobs:
    - bionic_py38_conda
    - bionic_py37_conda
