version: 2

jobs:
  bionic_gcc7_conda:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_gcc7_conda.sh

workflows:
  version: 2
  all_builds:
    jobs:
    - bionic_gcc7_conda
